
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC+3
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    property-naming-strategy: SNAKE_CASE

application:

  utils:
    time-service:
      zone: Europe/Istanbul

  security:
    jwt:
      secret-key: b0982c7360d5600030de94c0bb609ce9808a8a56227f2c94211e9d727d20342a
      expiration: 43200000 # 86400000 # a day || 24 * 60 * 60 * 1000
      refresh-token:
        expiration: 302400000 # 7 days

  cors:
    allowed-origins:
      - http://localhost:3000
      - http://localhost:5173
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    allowed-headers: \*